name: xmp
description: XMP module helps to extract xmp data from images.
version: 1.0.2
homepage: https://github.com/justkawal/xmp

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^6.0.0
  #utility: ^1.0.1  This is causing an issue...

#dev_dependencies:
